spring:
  datasource:
    url: jdbc:mysql://issue-tracker-db.cfwu6aug6ywt.ap-northeast-2.rds.amazonaws.com:3306/issue_tracker_db?serverTimezone=Asia/Seoul
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    access-key: ${JWT_ACCESS_KEY}
    refresh-key: ${JWT_REFRESH_KEY}

  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${S3_BUCKET_NAME}
        url: ${S3_URL_NAME}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
