spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: info
    com.team5: debug

  file:
    name: /var/log/issue-tracker/app.log
