spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/issue_tracker
    username: root
    password: 1234
  sql:
    init:
      mode: never
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql

logging:
  level:
    root: info
    com.team5: debug

  file:
    name: logs/app-dev.log
