spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issue_tracker
    username: root
    password: 1234

logging:
  level:
    root: info
    com.team5: debug

  file:
    name: logs/app-dev.log
